[build]
  base = "/"
  publish = "dist/" 
  command = "npm run build"
  branch = "testing"

[functions]
  directory = "netlify/functions" # Ajusta esta ruta si es diferente en tu proyecto

[dev]
  command = "npm run start" 
  port = 9000